#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo.svg"
# use `x` with logo_width, example: "100x"
logo_width = "240x"
# logo text will only show when logo is missing.
logo_text = "Pextra"
# OpenGraph / Twitter Card metadata
description = "Pextra todo"
author = "Pextra Inc."
image = "images/logo.png"                # this image will be used as fallback if a page has no image of its own

# footer information
footer_info = "Lorem ipsum dolor sit sed dmi amet, consectetur adipiscing. Cdo tellus, sed condimentum volutpat."

# contact form action
contact_form_action = "https://formspree.io/f/xgernlzd" # contact form works with https://formspree.io

# copyright
copyright = "Copyright &copy; 2023 Pextra Inc. All rights reserved."

# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>"
custom_script = ""

# Main Sections
mainSections = ["blog"]

# reading time for blog posts
reading_time = true

# contact information
[contact_info]
address = "2118 Thornridge Cir. Syracuse, Connecticut 35624"
phone = ["+704-555-0127", "+205-857-2321", "+002-569-6969"]
email = ["enterprise@pextra.cloud", "support@pextra.cloud"]

# imaging processing
[imaging]
# Default JPEG or WebP quality setting. Default is 100.
quality = 100

# Preloader
[preloader]
enable = true
preloader = "images/favicon.png" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = true
label = "Try Now"
link = "/products/cloudenvironment#demo"

# cookies
[cookies]
enable = true
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "Close"

# call-to-action
[cta]
enable = true
title = "Meet With Our Experts"
content = "Find out how Pextra can help your business.<br>Get a *free* migration plan with a timeline and cost estimate."
button = "Contact Us"
button_link = "https://gethugothemes.com/products/andromeda/"

############################# social site ########################
[[social]]
title = "Find us on GitHub!"
icon = "lab la-github" # https://icons8.com/line-awesome
link = "https://github.com/PextraCloud"

[[social]]
title = "AndromedaTweet"
icon = "lab la-twitter"  # https://icons8.com/line-awesome
link = "#!"

[[social]]
title = "AndromedaIn"
icon = "lab la-linkedin-in" # https://icons8.com/line-awesome
link = "#!"

[[social]]
title = "AndromedaPin"
icon = "lab la-pinterest" # https://icons8.com/line-awesome
link = "#!"
